# Generated by Django 6.0.4 on 2026-05-20 02:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ensure the django_auth schema exists (it is pre-created in production
        # by docker/postgres/init/001_schemas.sql but must be idempotently
        # created in test databases that start from scratch).
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS django_auth",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="DevUserUuid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dev_uuid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dev user UUID mapping",
                "db_table": 'django_auth"."dev_user_uuid',
            },
        ),
    ]
