-- FieldMark domain schema: table definitions.
--
-- Infrastructure-owned per ADR-014. This script is mounted into the postgres
-- container at /docker-entrypoint-initdb.d/010_domain_tables.sql and runs
-- automatically on first container startup after 001_schemas.sql.
--
-- The `domain` schema is shared by all three stacks (.NET, Django, Go/Fiber).
-- No framework migration tooling is permitted to CREATE, ALTER, or DROP tables
-- in this schema. Framework ORMs map to these tables; they do not own them.
--
-- User identity is framework-local (ADR-012). All domain rows reference users
-- only through opaque UUID columns; there are no foreign keys from domain.*
-- to any auth schema (django_auth, dotnet_auth, fiber_auth).
--
-- Enum-like fields use VARCHAR + CHECK constraints, not Postgres ENUM types,
-- to ensure schema evolution is consistent across all three stacks (ADR-014).
-- All timestamps are TIMESTAMPTZ. UUIDs are generated by application code at
-- runtime; seed data in 020_domain_seed.sql uses hardcoded UUIDs.

-- ---------------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------------

CREATE TABLE domain.trade_type (
    id          UUID        PRIMARY KEY,
    code        VARCHAR(32) UNIQUE NOT NULL,
    name        VARCHAR(120)       NOT NULL,
    description TEXT,
    active      BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE TABLE domain.violation_category (
    id               UUID        PRIMARY KEY,
    code             VARCHAR(32) UNIQUE NOT NULL,
    name             VARCHAR(200)       NOT NULL,
    trade_type_id    UUID        REFERENCES domain.trade_type(id),
    default_severity VARCHAR(16)        NOT NULL,
    description      TEXT,
    active           BOOLEAN     NOT NULL DEFAULT TRUE,
    CHECK (default_severity IN ('Low', 'Medium', 'High', 'Critical'))
);

CREATE TABLE domain.compliance_rule (
    id          UUID         PRIMARY KEY,
    code        VARCHAR(64)  UNIQUE NOT NULL,
    name        VARCHAR(200)        NOT NULL,
    description TEXT                NOT NULL,
    rule_kind   VARCHAR(32)         NOT NULL,
    parameters  JSONB               NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CHECK (rule_kind IN ('ScoringPenalty', 'ClosureGate'))
);

-- ---------------------------------------------------------------------------
-- Project aggregate
-- ---------------------------------------------------------------------------

CREATE TABLE domain.project (
    id                      UUID         PRIMARY KEY,
    code                    VARCHAR(32)  UNIQUE NOT NULL,
    name                    VARCHAR(200)        NOT NULL,
    description             TEXT,
    status                  VARCHAR(16)         NOT NULL,
    start_date              DATE                NOT NULL,
    target_completion_date  DATE,
    actual_closed_at        TIMESTAMPTZ,
    compliance_score        INTEGER      NOT NULL DEFAULT 100,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK (compliance_score BETWEEN 0 AND 100),
    CHECK (status IN ('Active', 'OnHold', 'Closed'))
);

CREATE TABLE domain.job_site (
    id         UUID         PRIMARY KEY,
    project_id UUID         NOT NULL REFERENCES domain.project(id) ON DELETE CASCADE,
    label      VARCHAR(120)        NOT NULL,
    address    VARCHAR(300)
);

-- Many-to-many: project ↔ trade_type. Drives required-inspection rules and
-- the closure gate (RequiredInspectionPerTrade).
CREATE TABLE domain.project_trade_scope (
    project_id    UUID NOT NULL REFERENCES domain.project(id)    ON DELETE CASCADE,
    trade_type_id UUID NOT NULL REFERENCES domain.trade_type(id),
    PRIMARY KEY (project_id, trade_type_id)
);

-- Project ↔ inspector assignment. user_id is an opaque reference to a
-- framework-local auth record; no FK to any auth schema (ADR-012).
CREATE TABLE domain.project_inspector (
    project_id UUID NOT NULL REFERENCES domain.project(id) ON DELETE CASCADE,
    user_id    UUID NOT NULL,
    PRIMARY KEY (project_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Inspection aggregate
-- ---------------------------------------------------------------------------

CREATE TABLE domain.inspection (
    id            UUID        PRIMARY KEY,
    project_id    UUID        NOT NULL REFERENCES domain.project(id),
    trade_type_id UUID        NOT NULL REFERENCES domain.trade_type(id),
    inspector_id  UUID        NOT NULL,                    -- opaque user ref; no FK
    scheduled_for TIMESTAMPTZ        NOT NULL,
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    status        VARCHAR(16)        NOT NULL,
    outcome       VARCHAR(16),
    notes         TEXT,
    created_at    TIMESTAMPTZ        NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ        NOT NULL DEFAULT now(),
    CHECK (status  IN ('Scheduled', 'InProgress', 'Completed', 'Cancelled')),
    CHECK (outcome IS NULL OR outcome IN ('Pass', 'Fail', 'Conditional')),
    -- outcome is set if and only if status is Completed
    CHECK ((status = 'Completed') = (outcome IS NOT NULL)),
    -- completed_at is set if and only if status is Completed
    CHECK ((status = 'Completed') = (completed_at IS NOT NULL))
);

-- finding.spawned_violation_id is a forward reference to domain.violation,
-- which does not exist yet. The column is created nullable here; the FK
-- constraint is added via ALTER TABLE after domain.violation is created below.
CREATE TABLE domain.finding (
    id                   UUID        PRIMARY KEY,
    inspection_id        UUID        NOT NULL REFERENCES domain.inspection(id),
    violation_category_id UUID       NOT NULL REFERENCES domain.violation_category(id),
    severity             VARCHAR(16)        NOT NULL,
    description          TEXT               NOT NULL,
    spawned_violation_id UUID,                            -- FK added after domain.violation
    CHECK (severity IN ('Low', 'Medium', 'High', 'Critical'))
);

-- ---------------------------------------------------------------------------
-- Violation aggregate
-- ---------------------------------------------------------------------------

CREATE TABLE domain.violation (
    id                   UUID        PRIMARY KEY,
    project_id           UUID        NOT NULL REFERENCES domain.project(id),
    origin_finding_id    UUID        NOT NULL REFERENCES domain.finding(id),
    violation_category_id UUID       NOT NULL REFERENCES domain.violation_category(id),
    severity             VARCHAR(16)        NOT NULL,
    status               VARCHAR(16)        NOT NULL,
    opened_at            TIMESTAMPTZ        NOT NULL,
    due_at               TIMESTAMPTZ        NOT NULL,
    resolved_at          TIMESTAMPTZ,
    voided_at            TIMESTAMPTZ,
    voided_reason        TEXT,
    description          TEXT               NOT NULL,
    created_at           TIMESTAMPTZ        NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ        NOT NULL DEFAULT now(),
    CHECK (status   IN ('Open', 'InProgress', 'Resolved', 'Voided')),
    CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    -- voided_at is set if and only if status is Voided
    CHECK ((status = 'Voided')   = (voided_at   IS NOT NULL)),
    -- resolved_at is set if and only if status is Resolved
    CHECK ((status = 'Resolved') = (resolved_at IS NOT NULL))
);

-- Back-fill the forward FK on finding now that domain.violation exists.
ALTER TABLE domain.finding
    ADD CONSTRAINT finding_spawned_violation_fk
    FOREIGN KEY (spawned_violation_id) REFERENCES domain.violation(id);

CREATE TABLE domain.corrective_action (
    id              UUID        PRIMARY KEY,
    violation_id    UUID        NOT NULL REFERENCES domain.violation(id),
    submitted_by_id UUID        NOT NULL,                  -- opaque user ref; no FK
    submitted_at    TIMESTAMPTZ        NOT NULL DEFAULT now(),
    description     TEXT               NOT NULL,
    evidence_ref    VARCHAR(500),                          -- placeholder; out of MVP scope
    status          VARCHAR(16)        NOT NULL,
    reviewed_by_id  UUID,                                  -- opaque user ref; no FK
    reviewed_at     TIMESTAMPTZ,
    review_notes    TEXT,
    CHECK (status IN ('Submitted', 'UnderReview', 'Approved', 'Rejected')),
    -- Defense-in-depth: primary enforcement is in CorrectiveAction.take_for_review
    CHECK (submitted_by_id <> reviewed_by_id OR reviewed_by_id IS NULL)
);

-- ---------------------------------------------------------------------------
-- Audit (append-only)
-- ---------------------------------------------------------------------------

-- No UPDATE or DELETE is permitted on this table. In production the owning
-- role is granted INSERT only. In development, application convention and
-- tests enforce the append-only constraint.
CREATE TABLE domain.audit_entry (
    id          UUID        PRIMARY KEY,
    occurred_at TIMESTAMPTZ        NOT NULL DEFAULT now(),
    actor_id    UUID        NOT NULL,                      -- opaque user ref; no FK
    action      VARCHAR(64)        NOT NULL,
    entity_type VARCHAR(64)        NOT NULL,
    entity_id   UUID               NOT NULL,
    project_id  UUID        REFERENCES domain.project(id), -- nullable; denormalized for query convenience
    before_state JSONB,
    after_state  JSONB,
    metadata     JSONB
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX idx_audit_entity
    ON domain.audit_entry (entity_type, entity_id);

CREATE INDEX idx_audit_project
    ON domain.audit_entry (project_id, occurred_at DESC);

CREATE INDEX idx_inspection_project_status
    ON domain.inspection (project_id, status);

CREATE INDEX idx_violation_project_status
    ON domain.violation (project_id, status);

-- Partial index: only rows that can become overdue are worth indexing for
-- the daily recalc and compliance-score queries.
CREATE INDEX idx_violation_due
    ON domain.violation (due_at)
    WHERE status IN ('Open', 'InProgress');
