"""
Django settings for fieldmark project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from psycopg.conninfo import conninfo_to_dict

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-u*&h8grkaw21(y#1zlu2*l9h#x+odhj8c88*fjfu8t9oh3#!do"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fieldmark",
    "projects",
    "inspections",
    "violations",
    "audit",
    "compliance",
    "reference",
    "grid",
    "tools",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login"

ROOT_URLCONF = "fieldmark.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "fieldmark.context_processors.theme",
            ],
        },
    },
]

WSGI_APPLICATION = "fieldmark.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# FIELDMARK_DATABASE_URL takes precedence when non-blank/whitespace. The value
# is stripped before parsing so leading/trailing spaces do not reach
# conninfo_to_dict. psycopg.conninfo.conninfo_to_dict handles postgres:// URIs
# with proper URL-decoding; all query parameters (sslmode, connect_timeout,
# application_name, etc.) are forwarded so the URL is a lossless source of
# connection configuration.
_db_dsn = (os.environ.get("FIELDMARK_DATABASE_URL") or "").strip() or "postgres://fieldmark:fieldmark@localhost:5432/fieldmark"
_db = conninfo_to_dict(_db_dsn)

# Standard keys that map to top-level DATABASE dict entries; everything else
# from the parsed URL is forwarded to OPTIONS for psycopg to consume.
_DB_STANDARD_KEYS = {"dbname", "user", "password", "host", "port"}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _db.get("dbname", "fieldmark"),
        "USER": _db.get("user", "fieldmark"),
        "PASSWORD": _db.get("password", "fieldmark"),
        "HOST": _db.get("host", "localhost"),
        "PORT": str(_db.get("port", 5432)),
        "OPTIONS": {
            # Architecture D7: chosen mechanism for django_auth schema isolation.
            # search_path routes all unqualified CREATE TABLEs (auth, sessions,
            # admin, contenttypes, migrations) into django_auth automatically.
            # Supersedes the routers.py approach shown in the architecture directory
            # diagram — no DatabaseRouter or per-model db_table overrides needed.
            # Domain models are Meta.managed=False with schema-qualified db_table
            # and are unaffected. Login/logout wiring lands in Story 1.11.
            "options": "-c search_path=django_auth,public",
            # Forward all non-standard connection parameters from the URL
            # (sslmode, sslrootcert, connect_timeout, application_name, etc.).
            **{k: str(v) for k, v in _db.items() if k not in _DB_STANDARD_KEYS},
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Vendor assets live inside the project package's static/ directory.
# STATICFILES_DIRS makes them discoverable by the dev server and collectstatic
# without adding the project package to INSTALLED_APPS.
STATICFILES_DIRS = [BASE_DIR / "static"]
