[pytest]
DJANGO_SETTINGS_MODULE = fieldmark.settings
python_files = test_*.py *_test.py tests.py
addopts = -ra
testpaths =
    projects
    inspections
    violations
    audit
    compliance
    reference
    grid
    tools
