# Generated by Django 6.0.4 on 2026-05-27 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobSite",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": 'domain"."job_site',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("OnHold", "On Hold"),
                            ("Closed", "Closed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField()),
                ("target_completion_date", models.DateField(blank=True, null=True)),
                ("actual_closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "compliance_score",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": 'domain"."project',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectInspector",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "project_id",
                        "user_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
            ],
            options={
                "db_table": 'domain"."project_inspector',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTradeScope",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "project_id",
                        "trade_type_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trade_type_id", models.UUIDField()),
            ],
            options={
                "db_table": 'domain"."project_trade_scope',
                "managed": False,
            },
        ),
    ]
