# Generated by Django 6.0.4 on 2026-05-28 03:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "rule_kind",
                    models.CharField(
                        choices=[
                            ("ScoringPenalty", "Scoring Penalty"),
                            ("ClosureGate", "Closure Gate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("parameters", models.JSONField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": 'domain"."compliance_rule',
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TradeType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": 'domain"."trade_type',
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ViolationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("trade_type", models.UUIDField(db_column="trade_type_id", null=True)),
                (
                    "default_severity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": 'domain"."violation_category',
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
