# Generated by Django 6.0.4 on 2026-05-28 02:47

import uuid

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("actor_id", models.UUIDField()),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.UUIDField()),
                ("project_id", models.UUIDField(null=True)),
                ("before_state", models.JSONField(null=True)),
                ("after_state", models.JSONField(null=True)),
                ("metadata", models.JSONField(null=True)),
            ],
            options={
                "db_table": 'domain"."audit_entry',
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
